test_6_placing_order.py::FrontEndPlaceOrderTest::test_place_order_r6_4
--------------------------------------------------------------------
Last Page: http://127.0.0.1:8081/
  Browser: chrome
Timestamp: 1639194491  (Unix Timestamp)
     Date: Friday, December 10, 2021
     Time: 10:48:11 PM  (Eastern Daylight Time, UTC-05:00)
--------------------------------------------------------------------
Traceback: File "c:\users\briggs\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\briggs\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\Users\Briggs\Desktop\2021Classes\CISC327\327Repository\Cisc-327-Course-Project-Group-20\qbay_test\frontend\test_6_placing_order.py", line 278, in test_place_order_r6_4
    self.assert_element("#iPhoneEleven")
  File "C:\Users\Briggs\AppData\Roaming\Python\Python38\site-packages\seleniumbase\fixtures\base_case.py", line 8797, in assert_element
    self.wait_for_element_visible(selector, by=by, timeout=timeout)
  File "C:\Users\Briggs\AppData\Roaming\Python\Python38\site-packages\seleniumbase\fixtures\base_case.py", line 6239, in wait_for_element_visible
    return page_actions.wait_for_element_visible(
  File "C:\Users\Briggs\AppData\Roaming\Python\Python38\site-packages\seleniumbase\fixtures\page_actions.py", line 370, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "C:\Users\Briggs\AppData\Roaming\Python\Python38\site-packages\seleniumbase\fixtures\page_actions.py", line 163, in timeout_exception
    raise exception(message)
Exception: Message: 
 Element {#iPhoneEleven} was not present after 6 seconds!
